### ISSUE TITLE
Sort error

### ISSUE THREAD

**Issue by claresudbery** [lubien/bookmarker#23]
Hi
I'm running this tool on a current Chrome bookmark file but I'm getting the following error:
(KeyError) key :sort not found in: %{"children" => 
(and then it quotes the json from the bookmarks file).
I'm attaching the bookmarks file that I'm running the tool on.
[tw-bookmarks.txt](https://github.com/lubien/bookmarker/files/4140836/tw-bookmarks.txt)

**Comment by robmoggach** [comment]
Same error here:

```
key :sort not found in: %{"children" => [%{"date_added" => "13224181674586972", "guid" => "d02918bb-
...

...
"13110997040180213", ...}, %{...}, ...]}
    (bookmarker 1.0.0) lib/bookmarker/runner.ex:14: Bookmarker.Runner.order_bookmarks/1
    (bookmarker 1.0.0) lib/bookmarker/runner.ex:8: Bookmarker.Runner.run/1
    (elixir 1.10.4) lib/kernel/cli.ex:124: anonymous fn/3 in Kernel.CLI.exec_fun/2
```

**Comment by lubien** [comment]
Can I ask your elixir versions?

**Comment by robmoggach** [comment]
```
elixir -v
Elixir 1.10.4 (compiled with Erlang/OTP 23)
```

**Comment by urielfcampos** [comment]
Tried reproducing this which the included bookmark file, but couldnt reproduce.
